version: 0.2

phases:
  build:
    commands:
      - echo "Syncing ./ to s3://codepipeline-us-east-1-147372310736"
      - aws s3 sync "./" "s3://codepipeline-us-east-1-147372310736"
    finally:
      - echo "Build phase completed `date`"
